
SET client_min_messages TO WARNING; 
create schema if not exists ad;


DROP TABLE IF EXISTS adstudies;
CREATE TABLE adstudies(
  id                     INT             PRIMARY KEY GENERATED ALWAYS AS IDENTITY  (start with 1000001 increment by 1)
, sd_sid                 VARCHAR         NOT NULL
, display_title          VARCHAR         NULL
, brief_description      VARCHAR         NULL
, type_id                INT             NOT NULL default 0
, status_id        	     INT             NOT NULL default 0
, status_override        VARCHAR         NULL
, start_status_override  VARCHAR         NULL
, iec_flag               INT             NOT NULL default 0 
, ipd_sharing            VARCHAR         NULL
, ipd_sharing_plan       VARCHAR         NULL
, date_last_revised      Date            NULL
, dt_of_data_fetch 	     TIMESTAMP       NULL
, added_on               TIMESTAMPTZ     NOT NULL default now()
);
CREATE INDEX studies_sid ON adstudies(sd_sid);


DROP TABLE IF EXISTS adstudy_dates;
CREATE TABLE adstudy_dates(
  id                     INT             PRIMARY KEY GENERATED ALWAYS AS IDENTITY  (start with 1000001 increment by 1)
, sd_sid                 VARCHAR         NOT NULL
, reg_year               INT             NULL
, reg_month              INT             NULL
, reg_date_type          CHAR(1)         NULL
, start_year             INT             NULL
, start_month            INT             NULL
, start_date_type        CHAR(1)         NULL
, comp_year              INT             NULL
, comp_month             INT             NULL
, comp_date_type         CHAR(1)         NULL
, res_year               INT             NULL
, res_month              INT             NULL
, res_date_type          CHAR(1)         NULL
, added_on               TIMESTAMPTZ     NOT NULL default now()
);
CREATE INDEX study_dates_sid ON adstudy_dates(sd_sid);


DROP TABLE IF EXISTS adstudy_partics;
CREATE TABLE adstudy_partics(
  id                     INT             PRIMARY KEY GENERATED ALWAYS AS IDENTITY  (start with 1000001 increment by 1)
, sd_sid                 VARCHAR         NOT NULL
, enrolment_target       VARCHAR         NULL
, enrolment_final        VARCHAR         NULL
, enrolment_total        VARCHAR         NULL
, enrolment              VARCHAR         NULL
, enrolment_type         CHAR(1)         NULL
, gender_flag            CHAR(1)         NULL
, min_age_as_string      VARCHAR         NULL
, min_age                INT             NULL
, min_age_units_id       INT             NULL
, max_age_as_string      VARCHAR         NULL
, max_age                INT             NULL
, max_age_units_id       INT             NULL
, age_group_flag         INT             NOT NULL default 0
, added_on               TIMESTAMPTZ     NOT NULL default now()
);
CREATE INDEX study_partics_sid ON adstudy_partics(sd_sid);


DROP TABLE IF EXISTS adstudy_titles;
CREATE TABLE adstudy_titles(
  id                     INT             PRIMARY KEY GENERATED ALWAYS AS IDENTITY (start with 10000001 increment by 1)
, sd_sid                 VARCHAR         NOT NULL
, title_text             VARCHAR
, lang_code              VARCHAR         NOT NULL default 'en'
, is_default             BOOL
, is_public              BOOL
, is_scientific          BOOL
, is_acronym             BOOL
, comments               VARCHAR
, added_on               TIMESTAMPTZ     NOT NULL default now()
);
CREATE INDEX study_titles_sid ON adstudy_titles(sd_sid);


DROP TABLE IF EXISTS adstudy_identifiers;
CREATE TABLE adstudy_identifiers(
  id                     INT             NOT NULL GENERATED BY DEFAULT AS IDENTITY
, sd_sid                 VARCHAR         NOT NULL
, id_value               VARCHAR         NULL
, id_type_id             INT             NULL
, id_type                VARCHAR         NULL
, added_on               TIMESTAMPTZ     NOT NULL default now()
, coded_on               TIMESTAMPTZ     NULL    
);
CREATE INDEX study_identifiers_sid ON adstudy_identifiers(sd_sid);


DROP TABLE IF EXISTS adstudy_orgs;
CREATE TABLE adstudy_orgs(
  id                     INT             PRIMARY KEY GENERATED ALWAYS AS IDENTITY (start with 10000001 increment by 1)
, sd_sid                 VARCHAR         NOT NULL
, contrib_type           VARCHAR         NULL
, name                   VARCHAR         NULL
, country                VARCHAR         NULL
, ror_id                 VARCHAR         NULL
, cross_ref_id           VARCHAR         NULL
, sponsor_type           VARCHAR         NULL
, added_on               TIMESTAMPTZ     NOT NULL default now()
, coded_on               TIMESTAMPTZ     NULL    
);
CREATE INDEX study_orgs_sid ON adstudy_orgs(sd_sid);


DROP TABLE IF EXISTS adstudy_people;
CREATE TABLE adstudy_people(
  id                     INT             PRIMARY KEY GENERATED ALWAYS AS IDENTITY (start with 10000001 increment by 1)
, sd_sid                 VARCHAR         NOT NULL
, contrib_type           VARCHAR         NULL
, given_name             VARCHAR         NULL
, family_name            VARCHAR         NULL
, orcid_id               VARCHAR         NULL
, affiliation            VARCHAR         NULL
, email_domain           VARCHAR         NULL
, added_on               TIMESTAMPTZ     NOT NULL default now()
, coded_on               TIMESTAMPTZ     NULL    
);
CREATE INDEX study_people_sid ON adstudy_people(sd_sid);


DROP TABLE IF EXISTS adstudy_iec;
CREATE TABLE adstudy_iec(
  id                     INT             PRIMARY KEY GENERATED ALWAYS AS IDENTITY (start with 10000001 increment by 1)
, sd_sid                 VARCHAR         NOT NULL
, ie_type_id             INT                
, ie_num                 int          
, criterion              VARCHAR
, added_on               TIMESTAMPTZ     NOT NULL default now()
);
CREATE INDEX study_iec_sid ON adstudy_iec(sd_sid);


DROP TABLE IF EXISTS adstudy_locations;
CREATE TABLE adstudy_locations(
  id                     INT             PRIMARY KEY GENERATED ALWAYS AS IDENTITY (start with 10000001 increment by 1)
, sd_sid                 VARCHAR         NOT NULL
, facility               VARCHAR         NULL
, address                VARCHAR         NULL
, city_name              VARCHAR         NULL
, disamb_name            VARCHAR         NULL
, country_name           VARCHAR         NULL
, added_on               TIMESTAMPTZ     NOT NULL default now()
, coded_on               TIMESTAMPTZ     NULL    
);
CREATE INDEX study_locations_sid ON adstudy_locations(sd_sid);


DROP TABLE IF EXISTS adstudy_countries;
CREATE TABLE adstudy_countries(
  id                     INT             PRIMARY KEY GENERATED ALWAYS AS IDENTITY (start with 10000001 increment by 1)
, sd_sid                 VARCHAR         NOT NULL
, country_name           VARCHAR         NULL
, added_on               TIMESTAMPTZ     NOT NULL default now()
, coded_on               TIMESTAMPTZ     NULL    
);
CREATE INDEX study_countries_sid ON adstudy_countries(sd_sid);


DROP TABLE IF EXISTS adstudy_topics;
CREATE TABLE adstudy_topics(
  id                     INT             PRIMARY KEY GENERATED ALWAYS AS IDENTITY (start with 10000001 increment by 1)
, sd_sid                 VARCHAR         NOT NULL
, source                 VARCHAR         NULL    
, topic_type             VARCHAR         NULL
, value                  VARCHAR         NULL       
, added_on               TIMESTAMPTZ     NOT NULL default now()
, coded_on               TIMESTAMPTZ     NULL    
);
CREATE INDEX study_topics_sid ON adstudy_topics(sd_sid);


DROP TABLE IF EXISTS adstudy_conditions;
CREATE TABLE adstudy_conditions(
  id                     INT             PRIMARY KEY GENERATED ALWAYS AS IDENTITY (start with 10000001 increment by 1)
, sd_sid                 VARCHAR         NOT NULL
, class1                 VARCHAR         NULL
, class2                 VARCHAR         NULL
, specific               VARCHAR         NULL
, added_on               TIMESTAMPTZ     NOT NULL default now()
, coded_on               TIMESTAMPTZ     NULL    
);
CREATE INDEX study_conditions_sid ON adstudy_conditions(sd_sid);


DROP TABLE IF EXISTS adstudy_features;
CREATE TABLE adstudy_features(
  id                     INT             PRIMARY KEY GENERATED ALWAYS AS IDENTITY (start with 10000001 increment by 1)
, sd_sid                 VARCHAR         NOT NULL
, source                 VARCHAR         NULL
, feature_type           VARCHAR         NULL
, feature_value          VARCHAR         NULL
, added_on               TIMESTAMPTZ     NOT NULL default now()
);
CREATE INDEX study_features_sid ON adstudy_features(sd_sid);


DROP TABLE IF EXISTS adstudy_references;
CREATE TABLE adstudy_references(
  id                     INT             PRIMARY KEY GENERATED ALWAYS AS IDENTITY (start with 10000001 increment by 1)
, sd_sid                 VARCHAR         NOT NULL
, pmid                   VARCHAR         NULL
, citation               VARCHAR         NULL
, doi                    VARCHAR         NULL	
, type_id                INT             NULL
, comments               VARCHAR         NULL
, added_on               TIMESTAMPTZ     NOT NULL default now()
);
CREATE INDEX study_references_sid ON adstudy_references(sd_sid);


DROP TABLE IF EXISTS adstudy_ipd_available;
CREATE TABLE adstudy_ipd_available(
  id                     INT             PRIMARY KEY GENERATED ALWAYS AS IDENTITY (start with 10000001 increment by 1)
, sd_sid                 VARCHAR         NOT NULL
, ipd_name               VARCHAR         NULL
, ipd_type               VARCHAR         NULL
, ipd_url                VARCHAR         NULL
, ipd_comment            VARCHAR         NULL
, added_on               TIMESTAMPTZ     NOT NULL default now()
);
CREATE INDEX study_ipd_available_sid ON adstudy_ipd_available(sd_sid);


DROP TABLE IF EXISTS addata_objects;
CREATE TABLE addata_objects(
  id                     INT             GENERATED ALWAYS AS IDENTITY PRIMARY KEY
, sd_oid                 VARCHAR         NOT NULL
, sd_sid                 VARCHAR         NULL
, title                  VARCHAR         NULL
, version                VARCHAR         NULL
, display_title          VARCHAR         NULL
, doi                    VARCHAR         NULL 
, publication_year       INT             NULL
, object_class_id        INT             NULL
, object_type_id         INT             NULL
, managing_org           VARCHAR         NULL
, lang_code              VARCHAR         NULL
, access_type_id         INT             NULL
, access_details         VARCHAR         NULL
, access_details_url     VARCHAR         NULL
, eosc_category          INT             NULL
, datetime_of_data_fetch TIMESTAMPTZ     NULL
, added_on               TIMESTAMPTZ     NOT NULL default now()
, coded_on               TIMESTAMPTZ     NULL    
);    
CREATE INDEX data_objects_oid ON addata_objects(sd_oid);
CREATE INDEX data_objects_sid ON addata_objects(sd_sid);


DROP TABLE IF EXISTS adobject_datasets;
CREATE TABLE adobject_datasets(
  id                     INT             GENERATED ALWAYS AS IDENTITY PRIMARY KEY
, sd_oid                 VARCHAR         NULL
, record_keys_type_id    INT             NULL 
, record_keys_details    VARCHAR         NULL    
, deident_type_id        INT             NULL  
, deident_details        VARCHAR         NULL    
, consent_type_id        INT             NULL  
, consent_details        VARCHAR         NULL 
, added_on               TIMESTAMPTZ     NOT NULL default now()
);
CREATE INDEX object_datasets_oid ON adobject_datasets(sd_oid);


DROP TABLE IF EXISTS adobject_dates;
CREATE TABLE adobject_dates(
  id                     INT             GENERATED ALWAYS AS IDENTITY PRIMARY KEY
, sd_oid                 VARCHAR         NULL
, date_type_id           INT             NULL
, date_is_range          BOOLEAN         NULL default false
, date_as_string         VARCHAR         NULL
, start_year             INT             NULL
, start_month            INT             NULL
, start_day              INT             NULL
, end_year               INT             NULL
, end_month              INT             NULL
, end_day                INT             NULL
, details                VARCHAR         NULL
, added_on               TIMESTAMPTZ     NOT NULL default now()
);
CREATE INDEX object_dates_oid ON adobject_dates(sd_oid);


DROP TABLE IF EXISTS adobject_instances;
CREATE TABLE adobject_instances(
  id                     INT             GENERATED ALWAYS AS IDENTITY PRIMARY KEY
, sd_oid                 VARCHAR         NULL
, system                 VARCHAR         NULL
, url                    VARCHAR         NULL
, url_accessible         BOOLEAN         NULL
, resource_type_id       INT             NULL
, resource_size          VARCHAR         NULL
, resource_size_units    VARCHAR         NULL
, resource_comments      VARCHAR         NULL
, added_on               TIMESTAMPTZ     NOT NULL default now()
, coded_on               TIMESTAMPTZ     NULL    
);
CREATE INDEX object_instances_oid ON adobject_instances(sd_oid);


DROP TABLE IF EXISTS adobject_titles;
CREATE TABLE adobject_titles(
  id                     INT             GENERATED ALWAYS AS IDENTITY PRIMARY KEY
, sd_oid                 VARCHAR         NULL
, title_type_id          INT             NULL
, title_text             VARCHAR         NULL
, is_default             BOOLEAN         NULL
, comments               VARCHAR         NULL
, added_on               TIMESTAMPTZ     NOT NULL default now()
);
CREATE INDEX object_titles_oid ON adobject_titles(sd_oid);

SET client_min_messages TO NOTICE; 


