
SET client_min_messages TO WARNING; 
create schema if not exists ad;

DROP TABLE IF EXISTS ad.studies;
CREATE TABLE ad.studies(
  id                     INT             PRIMARY KEY GENERATED ALWAYS AS IDENTITY  (start with 1000001 increment by 1)
, sd_sid                 VARCHAR         NOT NULL
, display_title          VARCHAR         NULL
, title_lang_code        VARCHAR         NOT NULL default 'en'
, brief_description      VARCHAR         NULL
, type_id                INT             NOT NULL default 0
, status_id              INT             NOT NULL default 0
, is_ipd_sharing         VARCHAR         NULL
, ipd_sharing_plan       VARCHAR         NULL
, date_last_revised      Date            NULL
, dt_of_data_fetch       TIMESTAMP       NULL
, added_on               TIMESTAMPTZ     NOT NULL default now()
);
CREATE INDEX studies_sid ON ad.studies(sd_sid);

DROP TABLE IF EXISTS ad.study_dates;
CREATE TABLE ad.study_dates(
  id                     INT             PRIMARY KEY GENERATED ALWAYS AS IDENTITY  (start with 1000001 increment by 1)
, sd_sid                 VARCHAR         NOT NULL
, reg_year               INT             NULL
, reg_month              INT             NULL
, reg_date_type          CHAR(1)         NULL
, start_year             INT             NULL
, start_month            INT             NULL
, start_date_type        CHAR(1)         NULL
, comp_year              INT             NULL
, comp_month             INT             NULL
, comp_date_type         CHAR(1)         NULL
, res_year               INT             NULL
, res_month              INT             NULL
, res_date_type          CHAR(1)         NULL
, added_on               TIMESTAMPTZ     NOT NULL default now()
);
CREATE INDEX study_dates_sid ON ad.study_dates(sd_sid);

DROP TABLE IF EXISTS ad.study_participants;
CREATE TABLE ad.study_participants(
  id                     INT             PRIMARY KEY GENERATED ALWAYS AS IDENTITY  (start with 1000001 increment by 1)
, sd_sid                 VARCHAR         NOT NULL
, enrolment              VARCHAR         NULL
, enrolment_type         CHAR(1)         NULL
, gender_flag            CHAR(1)         NULL
, min_age                INT             NULL
, min_age_units_id       CHAR(1)         NULL
, max_age                INT             NULL
, max_age_units_id       CHAR(1)         NULL
, age_group_flag         INT             NOT NULL default 0
, iec_flag               INT             NOT NULL default 0 
, added_on               TIMESTAMPTZ     NOT NULL default now()
);
CREATE INDEX study_participants_sid ON ad.study_participants(sd_sid);

DROP TABLE IF EXISTS ad.study_titles;
CREATE TABLE ad.study_titles(
  id                     INT             PRIMARY KEY GENERATED ALWAYS AS IDENTITY (start with 10000001 increment by 1)
, sd_sid                 VARCHAR         NOT NULL
, title_text             VARCHAR         NOT NULL
, lang_code              VARCHAR         NOT NULL default 'en'
, is_public              BOOL            NULL
, is_scientific          BOOL            NULL
, is_acronym             BOOL            NULL
, is_display             BOOL            NULL
, comments               VARCHAR         NULL
, added_on               TIMESTAMPTZ     NOT NULL default now()
);
CREATE INDEX study_titles_sid ON ad.study_titles(sd_sid);


DROP TABLE IF EXISTS ad.study_identifiers;
CREATE TABLE ad.study_identifiers(
  id                     INT             NOT NULL GENERATED BY DEFAULT AS IDENTITY
, sd_sid                 VARCHAR         NOT NULL
, id_value               VARCHAR         NULL
, id_type_id             INT             NULL
, id_type                VARCHAR         NULL
, source_org_id          INT             NULL
, source_org             VARCHAR         NULL
, source_ror_id          VARCHAR         NULL
, id_date                VARCHAR         NULL
, id_link                VARCHAR         NULL
, added_on               TIMESTAMPTZ     NOT NULL default now()
, coded_on               TIMESTAMPTZ     NULL    
);
CREATE INDEX study_identifiers_sid ON ad.study_identifiers(sd_sid);


DROP TABLE IF EXISTS ad.study_orgs;
CREATE TABLE ad.study_orgs(
  id                     INT             PRIMARY KEY GENERATED ALWAYS AS IDENTITY (start with 10000001 increment by 1)
, sd_sid                 VARCHAR         NOT NULL
, org_id                 VARCHAR         NULL
, org_name               VARCHAR         NULL
, org_country            VARCHAR         NULL
, org_ror_id             VARCHAR         NULL
, is_sponsor             BOOL            NULL
, is_funder              BOOL            NULL
, is_collaborator        BOOL            NULL
, added_on               TIMESTAMPTZ     NOT NULL default now()
, coded_on               TIMESTAMPTZ     NULL    
);
CREATE INDEX study_orgs_sid ON ad.study_orgs(sd_sid);


DROP TABLE IF EXISTS ad.study_people;
CREATE TABLE ad.study_people(
  id                     INT             PRIMARY KEY GENERATED ALWAYS AS IDENTITY (start with 10000001 increment by 1)
, sd_sid                 VARCHAR         NOT NULL
, full_name              VARCHAR         NULL
, listed_as              VARCHAR         NULL
, orcid_id               VARCHAR         NULL
, affiliation            VARCHAR         NULL
, affil_org_id           INT             NULL
, affil_org_name         VARCHAR         NULL
, affil_org_country      VARCHAR         NULL
, affil_org_ror_id       VARCHAR         NULL
, added_on               TIMESTAMPTZ     NOT NULL default now()
, coded_on               TIMESTAMPTZ     NULL    
);
CREATE INDEX study_people_sid ON ad.study_people(sd_sid);


DROP TABLE IF EXISTS ad.study_iec;
CREATE TABLE ad.study_iec(
  id                     INT             PRIMARY KEY GENERATED ALWAYS AS IDENTITY (start with 10000001 increment by 1)
, sd_sid                 VARCHAR         NOT NULL
, seq_num                INT             NULL
, ie_type_id             INT             NULL    
, split_type             VARCHAR         NULL
, tag                    VARCHAR         NULL  
, indent_level           INT             NULL
, indent_seq_num         INT             NULL
, sequence_string         VARCHAR         NULL
, criterion              VARCHAR         NULL
, added_on               TIMESTAMPTZ     NOT NULL default now()
);
CREATE INDEX study_iec_sid ON ad.study_iec(sd_sid);


DROP TABLE IF EXISTS ad.study_locations;
CREATE TABLE ad.study_locations(
  id                     INT             PRIMARY KEY GENERATED ALWAYS AS IDENTITY (start with 10000001 increment by 1)
, sd_sid                 VARCHAR         NOT NULL
, fac_id                 INT             NULL
, fac_name               VARCHAR         NULL
, fac_ror_id             VARCHAR         NULL
, city_id                INT             NULL
, city_name              VARCHAR         NULL
, disamb_id              INT             NULL
, disamb_name            VARCHAR         NULL
, country_id             INT             NULL
, country_name           VARCHAR         NULL
, status_id              INT             NULL
, added_on               TIMESTAMPTZ     NOT NULL default now()
, coded_on               TIMESTAMPTZ     NULL           
);
CREATE INDEX study_locations_sid ON ad.study_locations(sd_sid);


DROP TABLE IF EXISTS ad.study_countries;
CREATE TABLE ad.study_countries(
  id                     INT             PRIMARY KEY GENERATED ALWAYS AS IDENTITY (start with 10000001 increment by 1)
, sd_sid                 VARCHAR         NOT NULL
, country_id             INT             NULL
, country_name           VARCHAR         NULL
, status_id              INT             NULL
, added_on               TIMESTAMPTZ     NOT NULL default now()
, coded_on               TIMESTAMPTZ     NULL  default now()       -- already coded when added                                   
);
CREATE INDEX study_countries_sid ON ad.study_countries(sd_sid);


DROP TABLE IF EXISTS ad.study_topics;
CREATE TABLE ad.study_topics(
  id                     INT             PRIMARY KEY GENERATED ALWAYS AS IDENTITY (start with 10000001 increment by 1)
, sd_sid                 VARCHAR         NOT NULL
, topic_type             VARCHAR         NULL
, original_value         VARCHAR         NULL  
, original_ct_type_id    INT             NULL
, original_ct_code       VARCHAR         NULL 
, mesh_code              VARCHAR         NULL
, mesh_value             VARCHAR         NULL   
, added_on               TIMESTAMPTZ     NOT NULL default now()
, coded_on               TIMESTAMPTZ     NULL    
);
CREATE INDEX study_topics_sid ON ad.study_topics(sd_sid);


DROP TABLE IF EXISTS ad.study_conditions;
CREATE TABLE ad.study_conditions(
  id                     INT             PRIMARY KEY GENERATED ALWAYS AS IDENTITY (start with 10000001 increment by 1)
, sd_sid                 VARCHAR         NOT NULL
, original_value         VARCHAR         NULL
, original_ct_type_id    INT             NULL
, original_ct_code       VARCHAR         NULL                 
, icd_code               VARCHAR         NULL
, icd_name               VARCHAR         NULL
, added_on               TIMESTAMPTZ     NOT NULL default now()
, coded_on               TIMESTAMPTZ     NULL
);
CREATE INDEX study_conditions_sid ON ad.study_conditions(sd_sid);


DROP TABLE IF EXISTS ad.study_features;
CREATE TABLE ad.study_features(
  id                     INT             PRIMARY KEY GENERATED ALWAYS AS IDENTITY (start with 10000001 increment by 1)
, sd_sid                 VARCHAR         NOT NULL
, feature_type           VARCHAR         NULL
, feature_value          VARCHAR         NULL
, added_on               TIMESTAMPTZ     NOT NULL default now()
);
CREATE INDEX study_features_sid ON ad.study_features(sd_sid);


DROP TABLE IF EXISTS ad.study_pubs;
CREATE TABLE ad.study_pubs(
  id                     INT             PRIMARY KEY GENERATED ALWAYS AS IDENTITY (start with 10000001 increment by 1)
, sd_sid                 VARCHAR         NOT NULL
, pub_type               VARCHAR         NULL
, pub_id                 VARCHAR         NULL	
, pub_id_type            VARCHAR         NULL	
, citation               VARCHAR         NULL
, pub_notes              VARCHAR         NULL
, doi                    VARCHAR         NULL	
, pmid                   VARCHAR         NULL
, pmcid                  VARCHAR         NULL	
, pubsite_url            VARCHAR         NULL
, date_created           DATE            NULL
, date_published         DATE            NULL
, date_updated           DATE            NULL
, publication_year       INT             NULL
, added_on               TIMESTAMPTZ     NOT NULL default now()
);
CREATE INDEX study_pubs_sid ON ad.study_pubs(sd_sid);


DROP TABLE IF EXISTS ad.study_objects;
CREATE TABLE ad.study_objects(
  id                     INT             PRIMARY KEY GENERATED ALWAYS AS IDENTITY (start with 10000001 increment by 1)
, sd_sid                 VARCHAR         NOT NULL
, object_type            VARCHAR         NULL	
, object_id              VARCHAR         NULL
, object_id_type         VARCHAR         NULL
, object_notes           VARCHAR         NULL	
, display_name           VARCHAR         NULL	
, access_url             VARCHAR         NULL	
, access_type            VARCHAR         NULL	
, instance_type          VARCHAR         NULL	
, instance_notes         VARCHAR         NULL
, date_created           DATE            NULL
, date_published         DATE            NULL
, date_updated           DATE            NULL
, publication_year       INT             NULL
, added_on               TIMESTAMPTZ     NOT NULL default now()
);
CREATE INDEX study_objects_sid ON ad.study_objects(sd_sid);

SET client_min_messages TO NOTICE; 