
SET client_min_messages TO WARNING; 
create schema if not exists sd;


DROP TABLE IF EXISTS sd.studies;
CREATE TABLE sd.studies(
  id                     INT             PRIMARY KEY GENERATED ALWAYS AS IDENTITY  (start with 1000001 increment by 1)
, sd_sid                 VARCHAR         NOT NULL
, display_title          VARCHAR         NULL
, brief_description      VARCHAR         NULL
, type_id                INT             NOT NULL default 0
, status_id        	     INT             NOT NULL default 0
, status_override        VARCHAR         NULL
, start_status_override  VARCHAR         NULL
, is_ipd_sharing         BOOLEAN         NULL
, ipd_sharing_plan       VARCHAR         NULL
, date_last_revised      Date            NULL
, dt_of_data_fetch 	     TIMESTAMP       NULL
, added_on               TIMESTAMPTZ     NOT NULL default now()
);
CREATE INDEX studies_sid ON sd.studies(sd_sid);


DROP TABLE IF EXISTS sd.study_dates;
CREATE TABLE sd.study_dates(
  id                     INT             PRIMARY KEY GENERATED ALWAYS AS IDENTITY  (start with 1000001 increment by 1)
, sd_sid                 VARCHAR         NOT NULL
, reg_year               INT             NULL
, reg_month              INT             NULL
, reg_date_type          CHAR(1)         NULL
, start_year             INT             NULL
, start_month            INT             NULL
, start_date_type        CHAR(1)         NULL
, comp_year              INT             NULL
, comp_month             INT             NULL
, comp_date_type         CHAR(1)         NULL
, res_year               INT             NULL
, res_month              INT             NULL
, res_date_type          CHAR(1)         NULL
, added_on               TIMESTAMPTZ     NOT NULL default now()
);
CREATE INDEX study_dates_sid ON sd.study_dates(sd_sid);


DROP TABLE IF EXISTS sd.study_participants;
CREATE TABLE sd.study_participants(
  id                     INT             PRIMARY KEY GENERATED ALWAYS AS IDENTITY  (start with 1000001 increment by 1)
, sd_sid                 VARCHAR         NOT NULL
, enrolment_target       VARCHAR         NULL
, enrolment_final        VARCHAR         NULL
, enrolment_total        VARCHAR         NULL
, enrolment              VARCHAR         NULL
, enrolment_type         CHAR(1)         NULL
, gender_string          VARCHAR         NULL
, gender_flag            CHAR(1)         NULL
, min_age_string         VARCHAR         NULL
, min_age                float           NULL
, min_age_units_id       CHAR(1)         NULL
, max_age_string         VARCHAR         NULL
, max_age                float           NULL
, max_age_units_id       CHAR(1)         NULL
, age_group_flag         INT             NOT NULL default 0
, iec_flag               INT             NOT NULL default 0 
, added_on               TIMESTAMPTZ     NOT NULL default now()
);
CREATE INDEX study_participants_sid ON sd.study_participants(sd_sid);


DROP TABLE IF EXISTS sd.study_titles;
CREATE TABLE sd.study_titles(
  id                     INT             PRIMARY KEY GENERATED ALWAYS AS IDENTITY (start with 10000001 increment by 1)
, sd_sid                 VARCHAR         NOT NULL
, title_text             VARCHAR         NOT NULL
, is_public              BOOL            NULL
, is_scientific          BOOL            NULL
, is_acronym             BOOL            NULL
, is_display             BOOL            NULL
, comments               VARCHAR         NULL
, added_on               TIMESTAMPTZ     NOT NULL default now()
);
CREATE INDEX study_titles_sid ON sd.study_titles(sd_sid);


DROP TABLE IF EXISTS sd.study_identifiers;
CREATE TABLE sd.study_identifiers(
  id                     INT             NOT NULL GENERATED BY DEFAULT AS IDENTITY
, sd_sid                 VARCHAR         NOT NULL
, id_value               VARCHAR         NULL
, id_type_id             INT             NULL
, id_type                VARCHAR         NULL
, added_on               TIMESTAMPTZ     NOT NULL default now()
);
CREATE INDEX study_identifiers_sid ON sd.study_identifiers(sd_sid);


DROP TABLE IF EXISTS sd.study_orgs;
CREATE TABLE sd.study_orgs(
  id                     INT             PRIMARY KEY GENERATED ALWAYS AS IDENTITY (start with 10000001 increment by 1)
, sd_sid                 VARCHAR         NOT NULL
, org_name               VARCHAR         NULL
, is_sponsor             BOOL            NULL
, is_funder              BOOL            NULL
, is_collaborator        BOOL            NULL
, org_country            VARCHAR         NULL
, org_ror_id             VARCHAR         NULL
, org_cref_id            VARCHAR         NULL
, added_on               TIMESTAMPTZ     NOT NULL default now()
);
CREATE INDEX study_orgs_sid ON sd.study_orgs(sd_sid);


DROP TABLE IF EXISTS sd.study_people;
CREATE TABLE sd.study_people(
  id                     INT             PRIMARY KEY GENERATED ALWAYS AS IDENTITY (start with 10000001 increment by 1)
, sd_sid                 VARCHAR         NOT NULL
, full_name              VARCHAR         NULL
, listed_as              VARCHAR         NULL
, orcid_id               VARCHAR         NULL
, affiliation            VARCHAR         NULL
, email_domain           VARCHAR         NULL
, added_on               TIMESTAMPTZ     NOT NULL default now()
);
CREATE INDEX study_people_sid ON sd.study_people(sd_sid);


DROP TABLE IF EXISTS sd.study_iec;
CREATE TABLE sd.study_iec(
  id                     INT             PRIMARY KEY GENERATED ALWAYS AS IDENTITY (start with 10000001 increment by 1)
, sd_sid                 VARCHAR         NOT NULL
, seq_num                INT             NULL
, ie_type_id             INT             NULL    
, split_type             VARCHAR         NULL
, tag                    VARCHAR         NULL  
, indent_level           INT             NULL
, indent_seq_num         INT             NULL
, sequence_string        VARCHAR         NULL
, criterion              VARCHAR         NULL
, added_on               TIMESTAMPTZ     NOT NULL default now()
);
CREATE INDEX study_iec_sid ON sd.study_iec(sd_sid);

-- change of names to facility and address

DROP TABLE IF EXISTS sd.study_locations;
CREATE TABLE sd.study_locations(
  id                     INT             PRIMARY KEY GENERATED ALWAYS AS IDENTITY (start with 10000001 increment by 1)
, sd_sid                 VARCHAR         NOT NULL
, fac_name               VARCHAR         NULL
, fac_address            VARCHAR         NULL
, city_name              VARCHAR         NULL
, disamb_name            VARCHAR         NULL
, country_name           VARCHAR         NULL
, added_on               TIMESTAMPTZ     NOT NULL default now()
);
CREATE INDEX study_locations_sid ON sd.study_locations(sd_sid);


DROP TABLE IF EXISTS sd.study_countries;
CREATE TABLE sd.study_countries(
  id                     INT             PRIMARY KEY GENERATED ALWAYS AS IDENTITY (start with 10000001 increment by 1)
, sd_sid                 VARCHAR         NOT NULL
, country_name           VARCHAR         NULL
, added_on               TIMESTAMPTZ     NOT NULL default now()
);
CREATE INDEX study_countries_sid ON sd.study_countries(sd_sid);


DROP TABLE IF EXISTS sd.study_topics;
CREATE TABLE sd.study_topics(
  id                     INT             PRIMARY KEY GENERATED ALWAYS AS IDENTITY (start with 10000001 increment by 1)
, sd_sid                 VARCHAR         NOT NULL
, source                 VARCHAR         NULL    
, topic_type             VARCHAR         NULL
, topic_value            VARCHAR         NULL       
, added_on               TIMESTAMPTZ     NOT NULL default now()
);
CREATE INDEX study_topics_sid ON sd.study_topics(sd_sid);


DROP TABLE IF EXISTS sd.study_conditions;
CREATE TABLE sd.study_conditions(
  id                     INT             PRIMARY KEY GENERATED ALWAYS AS IDENTITY (start with 10000001 increment by 1)
, sd_sid                 VARCHAR         NOT NULL
, class1                 VARCHAR         NULL
, class2                 VARCHAR         NULL
, specific               VARCHAR         NULL
, added_on               TIMESTAMPTZ     NOT NULL default now()
);
CREATE INDEX study_conditions_sid ON sd.study_conditions(sd_sid);


DROP TABLE IF EXISTS sd.study_features;
CREATE TABLE sd.study_features(
  id                     INT             PRIMARY KEY GENERATED ALWAYS AS IDENTITY (start with 10000001 increment by 1)
, sd_sid                 VARCHAR         NOT NULL
, source                 VARCHAR         NULL
, feature_type           VARCHAR         NULL
, feature_value          VARCHAR         NULL
, added_on               TIMESTAMPTZ     NOT NULL default now()
);
CREATE INDEX study_features_sid ON sd.study_features(sd_sid);


DROP TABLE IF EXISTS sd.study_pubs;
CREATE TABLE sd.study_pubs(
  id                     INT             GENERATED ALWAYS AS IDENTITY PRIMARY KEY
, sd_sid                 VARCHAR         NULL
, pub_type               VARCHAR         NULL
, details                VARCHAR         NULL
, external_url           VARCHAR         NULL
, linking_id             VARCHAR         NULL
, doi                    VARCHAR         NULL
, pmid                   VARCHAR         NULL
, pmcid                  VARCHAR         NULL
, date_created           DATE            NULL
, date_uploaded          DATE            NULL
, added_on               TIMESTAMPTZ     NOT NULL default now()
);
CREATE INDEX study_pubs_sid ON sd.study_pubs(sd_sid);


DROP TABLE IF EXISTS sd.study_objects;
CREATE TABLE sd.study_objects(
  id                     INT             GENERATED ALWAYS AS IDENTITY PRIMARY KEY
, sd_sid                 VARCHAR         NULL
, artefact_type          VARCHAR         NULL
, object_type            VARCHAR         NULL
, date_created           DATE            NULL
, date_uploaded          DATE            NULL
, link_url               VARCHAR         NULL
, gu_id                  VARCHAR         NULL
, file_name              VARCHAR         NULL
, object_description     VARCHAR         NULL
, object_filename        VARCHAR         NULL
, download_filename      VARCHAR         NULL
, output_version         VARCHAR         NULL
, object_length          INT             NULL
, mime_type              VARCHAR         NULL
, added_on               TIMESTAMPTZ     NOT NULL default now()
);
CREATE INDEX study_objects_sid ON sd.study_objects(sd_sid);


DROP TABLE IF EXISTS sd.study_attached_files;
CREATE TABLE sd.study_attached_files(
  id                     INT             GENERATED ALWAYS AS IDENTITY PRIMARY KEY
, sd_sid                 VARCHAR         NULL
, gu_id                  VARCHAR         NULL
, file_name              VARCHAR         NULL
, file_description       VARCHAR         NULL
, is_public              BOOLEAN         NULL
, mime_type              VARCHAR         NULL
, added_on               TIMESTAMPTZ     NOT NULL default now()
);
CREATE INDEX study_files_sid ON sd.study_attached_files(sd_sid);

SET client_min_messages TO NOTICE; 